### ISSUE TITLE
USER STORY: I want to earn and spend Glaze Drops

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#10]
EPIC: **Gamification**

As a **registered user** I can **earn Glaze Drops based on my interactions with the website** so that **I feel encouraged to engage actively in the community**.

**Acceptance Criteria**:
- [ ] The user earns Glaze Drops for actions like uploading design requests, leaving comments, or voting for a design
- [ ] The total balance of Glaze Drops is visible to the registered user in a personal greeting on the home page

**Tasks**:
- [ ] Define actions that earn Glaze Drops and set point values
- [ ] Update user balances dynamically based on ACTIONS
