### ISSUE TITLE
USER STORY: New user wants to browse the blog page

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#12]
EPIC: **New User Experience**

As a **new user** I can **browse the blog page and see posts made by registered users, including their username, timestamp, content, optional images, and totals of vote** so that **I can understand community discussions and potentially gain some insights without participating myself**.

**Acceptance Criteria**:
- [ ] The page layout of the blog is clear and strctured
- [ ] Posts include details: username of author, timestamp, text content, optionally images, total vote count of community members
- [ ] Responsiveness: Posts should be readable on all screen sizes, therefore collapsed on smaller screens
- [ ] Unregistered visitors can only browse but not interact (post, comment, vote) - a visual cue (greyed out buttons and message in posting form) indicates that interactions require registration
- [ ] Error handling: Alternative display if no posts available or cannot be shown

**Task**
- [ ] Card layout for blog posts 
- [ ] Solution for posts without images
- [ ] Read more link for posts with longer content
- [ ] Backend structure to fetch posts and possibly sort them
- [ ] Visitor restriction: add logic to disable interactivity for non-registered user
- [ ] Display message on post form for non-registered user
