### ISSUE TITLE
USER STORY: I want to see that I need to register to post, comment and vote

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#13]
EPIC: **New User Experience**

As a **a new user** I can **clearly see and understand that interacting with the website requires registration** so that **I can see the need of signing up**.

**Acceptance Criteria**:
- [ ] All interactive elements are visible but disabled and greyed out for new users.
- [ ] The posting form displays a message that explains the need to sign up to participate.
- [ ] All registration prompts include a link directing the user to the registration page.

**Tasks**:
- [ ] A short, visible message on the blog page explains the need to register to participate (e.g. "Join us to post your ideas, comment, and vote for your favorites!").
- [ ] Style disabled buttons and other elements.
- [ ] Insert links that redirect to registration form.
