### ISSUE TITLE
USER STORY: I want to understand everything in "About the Glaze Craze"

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#15]
EPIC: **Community Interaction**

As a **user** I can **explore a dedicated "About the Glaze Craze" page that explains the shop, community blog, and Glaze Drops system in detail** so that **I can understand the website's purpose and incentives**.

**Acceptance Criteria**:
- [ ] Distinct sections that explain the purpose and rules of a) the shop, b) the community blog, c) restrictions for non-registered users, and d) the reward system of Glaze Drops.
- [ ] The page includes icons for visual engagement and clear understanding.
- [ ] Call-to-action that encourages to register after learning about the website's features.
- [ ] Responsiveness and readability across various devices and screen sizes.

**Tasks**:
- [ ] Add a link to short bio on home page and menu item in nav bar that lead to "About the Glaze Craze" page.
- [ ] Content.
- [ ] Add icons to sections.
- [ ] Insert call-to-action that redirects to registration page.

**Comment by nathiedeheyl** [comment]
For a "sign up" call to action btn, see for instance [this tutorial](https://youtu.be/GdrbE-s5DgQ?si=Oc-r-b5ztlU8q2j0&t=404)
