### ISSUE TITLE
USER STORY: I want to land on the shop page and see the available pottery items and a brief introduction to the site

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#2]
EPIC: <epic>**New User Experience**</epic>

As a **new user** I can **see available pottery items and a brief intro on the landing page** so that **I see what the website is about and what it offers**

**Acceptance Criteria**:
- [ ] The shop page loads by default when visiting the site
- [ ] A brief text introduction is displayed on the shop page
- [ ] The user can see a grid of available items, each with an image, description, and price

**Tasks**:
- [ ] Create a homepage layout that defaults to the shop page
- [ ] Add a brief introductory section with a description of the site’s mission
- [ ] Display a grid of pottery items with images, names, and prices
- [ ] Implement responsive design for mobile, tablet, and desktop

**Comment by nathiedeheyl** [comment]
Must To Do: 
- [x] set up sylesheet, html file for the homepage/shop
- [x] title header with the website name "the Glaze craze" 
- [ ] change header to one line nav, add responsiveness to header + make nav bar toggle down for small screens
- [ ] sticky header and nav bar
- [ ] add invisible personal greeting for later
- [ ] horizontal nav bar with links to further pages (shop, blog, about, sign up, profile)
- [ ] nav bar: sign up/log becomes log out when user is logged in
- [ ] column 1: add pottery items with item title and short teaser
- [ ] column 2: add section with placeholder for artist's short bio
- [ ] responsiveness: stack columns 2 on top then 1 on smaller screens

Could-have:
- [ ] JS event: make artist short bio disappear upon scroll down and reappear upon scroll to top
