### ISSUE TITLE
USER STORY: I want to see a short introduction to the artist on the home page

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#3]
EPIC: <epic>**New User Experience**</epic>

As a **new user** I can **see a short intro on the home page**, so I **understand the mission of the project**.

**Acceptance Criteria**:
- [ ] The homepage features an "short bio" as a teaser about the artist with a photo
- [ ] Intro bio explains the website's purpose

**Tasks**:
- [ ] Second column next to grid with the artist's "short bio"
- [ ] Add a photo to short bio
- [ ] Ensure accessibility features
