### ISSUE TITLE
USER STORY: I want to view the navigation bar and see clearly labeled sections of the site

### ISSUE THREAD

**Issue by nathiedeheyl** [nathiedeheyl/pp4_glaze-craze#4]
EPIC: **New User Experience**

As a **new user* I can **see a navigation bar with clearly labeled sections of the site** so that **I know where to find which information**.

**Acceptance Criteria**:
- [ ] The navigation bar is visible on all pages
- [ ] Sections include home/shop, blog, about, and sign up/in
- [ ] Each link redirects to the corresponding page

**Tasks**:
- [ ] Build a responsive navigation bar with clearly labeled links
- [ ] Make nav bar a hamburger menu with toggle down for smaller screens
- [ ] Highlight the active page in the navigation bar
